#!/bin/bash
TO="9566569265a@gmail.com,princevermadevops@gmail.com,austycool100893@gmail.com"
HOSTNAME=$(hostname)
DATE=$(date "+%Y-%m-%d %H:%M:%S")
CPUSAGE=$(top -b -n 1 d1 | grep "Cpu(s)" | awk '{ print $2 }')
MEMUSAGE=$(free | grep Mem |awk '{ print $3/$2 * 100.0}')
DISKUSAGE=$(df -P|column -t |awk '{print $5}'| tail -n 1)

echo "Hostname   = $HOSTNAME
      Date&Time  = $DATE
      CPU        = $CPUSAGE
      Mem        = $MEMUSAGE
      Disk       = $DISKUSAGE"|sendmail $TO

for i in `cat /scripts/hostlist`;
do
RHOSTNAME=$(ssh $i hostname)
RDATE=$(ssh $i 'date "+%Y-%m-%d %H:%M:%S"')
RCPUSAGE=$(ssh $i top -b -n 1 d1 | grep "Cpu(s)" | awk '{ print $2 }')
RMEMUSAGE=$(ssh $i free | grep Mem |awk '{ print $3/$2 * 100.0}')
RDISKUSAGE=$(ssh $i df -P|column -t |awk '{print $5}'| tail -n 1)


echo "Hostname   = $RHOSTNAME
      Date&Time  = $RDATE
      CPU        = $RCPUSAGE
      Mem        = $RMEMUSAGE
      Disk       = $RDISKUSAGE"|sendmail $TO
done
